apiVersion: v1
kind: Pod
metadata:
  name: es-debug
spec:
  restartPolicy: Never
  volumes:
    - name: es-ca-certs
      secret:
        secretName: es-ca-certs
  containers:
    - name: debug
      image: alpine
      command:
        ["sh", "-c", "trap 'exit' SIGTERM SIGINT; while true; do sleep 1; done"]
      volumeMounts:
        - name: es-ca-certs
          mountPath: /ca-certs
