# generated by gen_node_pool_od.py
resource "google_container_node_pool" "od_e2_standard_2" {
  name     = "od-e2-standard-2"
  cluster  = google_container_cluster.zero.name
  location = google_container_cluster.zero.location

  autoscaling {
    min_node_count = 0
    max_node_count = 5
  }

  network_config {
    enable_private_nodes = true
  }

  node_config {
    machine_type = "e2-standard-2"
    disk_size_gb = 32
  }
}

# generated by gen_node_pool_od.py
resource "google_container_node_pool" "od_e2_standard_4" {
  name     = "od-e2-standard-4"
  cluster  = google_container_cluster.zero.name
  location = google_container_cluster.zero.location

  autoscaling {
    min_node_count = 0
    max_node_count = 5
  }

  network_config {
    enable_private_nodes = true
  }

  node_config {
    machine_type = "e2-standard-4"
    disk_size_gb = 32
  }
}

# generated by gen_node_pool_od.py
resource "google_container_node_pool" "od_e2_highmem_2" {
  name     = "od-e2-highmem-2"
  cluster  = google_container_cluster.zero.name
  location = google_container_cluster.zero.location

  autoscaling {
    min_node_count = 0
    max_node_count = 5
  }

  network_config {
    enable_private_nodes = true
  }

  node_config {
    machine_type = "e2-highmem-2"
    disk_size_gb = 32
  }
}

# generated by gen_node_pool_od.py
resource "google_container_node_pool" "od_e2_highmem_4" {
  name     = "od-e2-highmem-4"
  cluster  = google_container_cluster.zero.name
  location = google_container_cluster.zero.location

  autoscaling {
    min_node_count = 0
    max_node_count = 5
  }

  network_config {
    enable_private_nodes = true
  }

  node_config {
    machine_type = "e2-highmem-4"
    disk_size_gb = 32
  }
}
